name: Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: false
        description: Who to greet
        options:
          - monalisa
          - aphrodite

jobs:
  call-reusable-testing-linting:
    uses: polyccon/github-action-reusable-workflows/.github/workflows/reusable-python-testing-linting.yml@main
    with:
      foo: "Demoing dynamically passing env variables"